/*
 * This file is generated by jOOQ.
 */
package ru.khehelk.practice.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import ru.khehelk.practice.jooq.tables.Users;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_USERS_AGE = Internal.createIndex(DSL.name("idx_users_age"), Users.USERS, new OrderField[] { Users.USERS.AGE }, false);
    public static final Index IDX_USERS_CREATED_AT = Internal.createIndex(DSL.name("idx_users_created_at"), Users.USERS, new OrderField[] { Users.USERS.CREATED_AT }, false);
    public static final Index IDX_USERS_STATUS = Internal.createIndex(DSL.name("idx_users_status"), Users.USERS, new OrderField[] { Users.USERS.STATUS }, false);
}
