/*
 * This file is generated by jOOQ.
 */
package ru.khehelk.practice.jooq.tables.records;


import java.time.LocalDateTime;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import ru.khehelk.practice.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public UsersRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.users.username</code>.
     */
    public UsersRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.users.username</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public UsersRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    @NotNull
    @Size(max = 255)
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.first_name</code>.
     */
    public UsersRecord setFirstName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.users.first_name</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.last_name</code>.
     */
    public UsersRecord setLastName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.users.last_name</code>.
     */
    @NotNull
    @Size(max = 100)
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.users.age</code>.
     */
    public UsersRecord setAge(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.users.age</code>.
     */
    @NotNull
    public Integer getAge() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.users.status</code>.
     */
    public UsersRecord setStatus(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.users.status</code>.
     */
    @Size(max = 20)
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    public UsersRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.users.updated_at</code>.
     */
    public UsersRecord setUpdatedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.users.last_login</code>.
     */
    public UsersRecord setLastLogin(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.users.last_login</code>.
     */
    public LocalDateTime getLastLogin() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Long id, String username, String email, String firstName, String lastName, Integer age, String status, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime lastLogin) {
        super(Users.USERS);

        setId(id);
        setUsername(username);
        setEmail(email);
        setFirstName(firstName);
        setLastName(lastName);
        setAge(age);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setLastLogin(lastLogin);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(ru.khehelk.practice.jooq.tables.pojos.Users value) {
        super(Users.USERS);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setEmail(value.getEmail());
            setFirstName(value.getFirstName());
            setLastName(value.getLastName());
            setAge(value.getAge());
            setStatus(value.getStatus());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            setLastLogin(value.getLastLogin());
            resetChangedOnNotNull();
        }
    }
}
