version: '3.9'

services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practice_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql

  clickhouse:
    image: clickhouse/clickhouse-server:26.2
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: practice_db
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1

volumes:
  pg_data:
  ch_data: